
services:
  mysql:
    image: mysql:8.0
    container_name: workway_mysql
    restart: always
    env_file: .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: workway_adminer
    restart: always
    ports:
      - "8080:8080"

  backend:
    build: ./backend
    container_name: workway-backend
    ports:
      - "5001:5000"
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
    env_file: 
     - .env


  frontend:
    build: ./frontend
    container_name: workway-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro

volumes:
  mysql_data: